apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: jcontainerregistry.azurecr.io/frontend:latest
        env:
        - name: BackendUrlENV
          value: "http://104.40.7.46:8030/data"
        ports:
        - containerPort: 8030
      imagePullSecrets:
      - name: jazurecontainersecret
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    run: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 8030
    protocol: TCP
  selector:
    app: frontend

