apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend1
  labels:
    app: backend1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend1
  template:
    metadata:
      labels:
        app: backend1
    spec:
      containers:
      - name: backend1
        image: jcontainerregistry.azurecr.io/backend:latest
        ports:
        - containerPort: 8030
      imagePullSecrets:
      - name: jazurecontainersecret
---
apiVersion: v1
kind: Service
metadata:
  name: backend1
  labels:
    run: backend1
spec:
  type: LoadBalancer
  ports:
  - port: 8030
    protocol: TCP
  selector:
    app: backend1

