apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend2
  labels:
    app: backend2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend2
  template:
    metadata:
      labels:
        app: backend2
    spec:
      containers:
      - name: backend2
        image: jcontainerregistry.azurecr.io/backend:v2
        ports:
        - containerPort: 8030
      imagePullSecrets:
      - name: jazurecontainersecret
---
apiVersion: v1
kind: Service
metadata:
  name: backend2
  labels:
    run: backend2
spec:
  type: LoadBalancer
  ports:
  - port: 8030
    protocol: TCP
  selector:
    app: backend2

